// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MSGBroker is an autogenerated mock type for the MSGBroker type
type MSGBroker struct {
	mock.Mock
}

// Publish provides a mock function with given fields: subject, event
func (_m *MSGBroker) Publish(subject string, event []byte) {
	_m.Called(subject, event)
}

// NewMSGBroker creates a new instance of MSGBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMSGBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MSGBroker {
	mock := &MSGBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
